# Generated by Django 4.1.1 on 2022-09-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        default=280769620061070410912487809372082649544,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "clef",
                    models.CharField(
                        default="D33A44F43D2D11ED8643784F4397B9C8",
                        max_length=33,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[("CSV", "CSV"), ("UNKNOWN", "Unknown")],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("structure", models.JSONField()),
                ("data", models.JSONField()),
            ],
        ),
    ]
