# Generated by Django 4.1.1 on 2022-09-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataloader", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="clef",
            field=models.CharField(
                default="C38B84863DA111EDBB0E784F4397B9C8", max_length=33, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
