# Generated by Django 4.1.1 on 2022-09-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataloader", "0002_alter_fileupload_clef_alter_fileupload_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="clef",
            field=models.CharField(
                default="6CD8EA2E3DA211EDB319784F4397B9C8", max_length=33, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
