# Generated by Django 4.1.1 on 2022-09-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataloader", "0003_alter_fileupload_clef_alter_fileupload_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fileupload",
            name="id",
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="clef",
            field=models.CharField(
                default="761745D63DA211ED8405784F4397B9C8",
                max_length=33,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
