# Generated by Django 4.1.1 on 2022-09-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataloader", "0004_remove_fileupload_id_alter_fileupload_clef"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="clef",
            field=models.CharField(
                default="82C2BF183DA211ED896D784F4397B9C8",
                max_length=33,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
